### ISSUE TITLE
Use Uniform Bulletting

### ISSUE THREAD

**Issue by grant** [GoogleCloudPlatform/awesome-google-cloud#30]
Thanks for the project!

This README.md would be more readable if the sections were uniformly lists, not a mix of lists and paragraphs. I'm also not sure why some product have a link to the product page and show the product description, and other products don't.

### ACTUAL

```
See the extensive list at [Awesome Cloud Run](https://github.com/steren/awesome-cloudrun).
```

### EXPECTED

```
- [Awesome Cloud Run](https://github.com/steren/awesome-cloudrun).
```

---

List of sections that have descriptions rather than (awesome) list items.

- Big Data
- Storage & Databases
- Cloud AI
- Cloud Run
- Compute

**Comment by tswast** [comment]
Makes sense to me. Happy to review a PR that reformats this.

I don't think there was any particular reason these weren't nested lists to begin with.

**Comment by grant** [comment]
> Makes sense to me. Happy to review a PR that reformats this.
> 
> I don't think there was any particular reason these weren't nested lists to begin with.

Cool. Here's a little PR: https://github.com/GoogleCloudPlatform/awesome-google-cloud/pull/36
